### ISSUE TITLE
Increment package.json major version number.

### ISSUE THREAD

**Issue by traviswimer** [traviswimer/grunt-not-constantinople#11]
A breaking change was implemented in #6 , so the version number needs changed to reflect that before publishing on npm.

**Comment by JamesMGreene** [comment]
You're a good SemVer citizen.  :+1:

**Comment by traviswimer** [comment]
Yea, but I honestly wish NPM would just remove the `~` and `^` concept. It would be a great idea if everyone followed the semver concept and no one ever made mistakes. In reality it just creates awful situations that are really hard to debug. I've actually set `save-exact` to `true` in my npm config and just use the specific version in new projects. I don't really see a downside.

Oh, and I've published `v1.0.0` to npm. :+1:
