### ISSUE TITLE
Incompatible with the "node_modules" folder structure in `npm@3`

### ISSUE THREAD

**Issue by JamesMGreene** [traviswimer/grunt-not-constantinople#3]
I ran into this issue today when I used `npm@3` to install  `grunt-not-constantinople`, which &mdash; as you know &mdash; has [`peerDependencies` on `grunt-contrib-clean`, `grunt-istanbul`, and `grunt-istanbul-coverage`](https://github.com/traviswimer/grunt-not-constantinople/blob/d236cff13b321b54bf1f0ddd3fb9bae9079cab04/tasks/not_constantinople.js#L44-L47):

```
Running "not_constantinople:coverage" (not_constantinople) task
Verifying property not_constantinople.coverage exists in config...OK
File: [no files]
Warning: Cannot find module 'grunt-contrib-clean' Use --force to continue.

Aborted due to warnings.
```

Realistically, the problem is in how `grunt.loadNpmTasks`/`grunt.task.loadNpmTasks` works... it is very specifically written to work in the `npm@<3` world as it relies on a `node_modules` directory existing as a child of the main directory rather than using a more robust mechanism like [`require.resolve`](https://nodejs.org/api/globals.html#globals_require_resolve) to traverse into module directories.

Ironically, with the current version of Grunt and `npm@3`, the [`grunt-loadNpmTasks`](https://www.npmjs.com/package/grunt-loadnpmtasks) Node module that I wrote a long time ago for a hierarchical codebase would now actually be applicable to a non-hierarchical codebase to solve this issue, too. :confused:

See https://github.com/gruntjs/grunt/issues/1355#issuecomment-175789630 for more background.

**Comment by traviswimer** [comment]
Interesting problem. What you said makes sense, but I wasn't able to reproduce it. Could this problem also be solved by just `npm install`-ing the peerDependencies in the project where `grunt-not-constantinople` is being used?

**Comment by JamesMGreene** [comment]
@traviswimer: I thought so at first but that did not work for me either.

If you are trying it within an existing project that was initially setup with `npm@<3`, make sure you blow away your `node_modules` folder before installing everything with `npm@3.x`.

**Comment by traviswimer** [comment]
Yea, I tried that. I even ran `npm cache clean` just to make sure.

I guess at least adding in `grunt-loadNpmTasks` somewhat simplifies things, so either way I'm not opposed to pulling it in.
